version: '3.9'

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    tty: true
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 0ti!psH838&*
    command: server /data --console-address ":9001"

  adminproject:
    build: 
      context: ./
      dockerfile: docker/laravel-app/Dockerfile
    container_name: adminproject
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - minio


# version: '3.9'
# services:
#   # smtp:
#   #   image: axllent/mailpit
#   #   container_name: smtp
#   #   restart: always
#   #   ports:
#   #     - 8025:8025
#   #     - 1025:1025
  
#   minio:
#     image: minio/minio
#     container_name: minio
#     restart: always
#     tty: true
#     ports:
#       - 9000:9000
#       - 9001:9001
#     environment:
#       MINIO_ROOT_USER: admin
#       MINIO_ROOT_PASSWORD: 0ti!psH838&*
#     command: server /data --console-address ":9001"

#   # redis:
#   #   image: redis/redis-stack
#   #   container_name: redis
#   #   restart: always
#   #   ports:
#   #     - 6379:6379
#   #     - 8001:8001
#   #   volumes:
#   #     - ./redis.conf:/usr/local/etc/redis/redis.conf
    
    
#   adminproject:
#     build: 
#       context: ./
#       dockerfile: docker/laravel-app/Dockerfile
#     container_name: adminproject
#     ports:
#       - 8000:8000
#       # - 80:81
#     volumes:
#       - ./docker/laravel-app/sites-available:/etc/nginx/sites-available
#       - ./docker/laravel-app/sites-enabled:/etc/nginx/sites-enabled